@baseURL = https://cna-orders.azurewebsites.net

//@baseURL = http://localhost:3080
@token = Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJTZWN1cml0eSBTZXJ2aWNlICgxLjAuMCkiLCJleHAiOjE2NjgyMDY1MDEsInN1YiI6IjYzNWJlMDkwZjFkMWJhN2NiMTdhNWY4YSIsImRhdGEiOnsiZmlyc3ROYW1lIjoiSm9obiIsImxhc3ROYW1lIjoiRG9lIiwiYWRkcmVzcyI6Ikphbi1NYWdudXMgSmFuc3NvbmluIGF1a2lvIDEiLCJwb3N0YWxDb2RlIjoiNTUwIiwiY2l0eSI6IkhlbHNpbmtpIiwiY291bnRyeSI6IkZpbmxhbmQiLCJlbWFpbCI6ImpvaG4uZG9lQGFyY2FkYS5maSJ9LCJpYXQiOjE2NjgxOTkzMDF9.g88qSp8d52cQl2aNAexH-OdDOXaZB4cPA8TVOIts5A5XUfZruvq2XrEtD2CnQQU19Ft1ui5DiQaS44V__Y2iijLXgBxNWZLbvyIDWqBVnWSJzQscjXZvG2x6ulX21vZc65febK3SbE60MICAP8K9uaKGQrnCRmW85S3ooDSVqMsKmVBSr-1pxw46cXZSukGsu-gbRof980rcEoKszzB9velWL6E8MdkS2-vway-Kz6579WGywNRKn75iw2JdPSmIjW7MKrUFsdGQrOIQuWkdGSwHjbmU_UpR7s0F7UXH4I0hWWV4mcJo71FLsTixWk8qA4XmcnPc6oO6EwULCQRReQ

###

GET {{baseURL}}/orders/
Authorization: {{token}}
Content-Type: application/json

###

GET {{baseURL}}/orders/customers
Authorization: {{token}}
Content-Type: application/json

###

POST {{baseURL}}/orders/
Authorization: {{token}}
Content-Type: application/json

{
    "date": "2022-11-1",
    "products": [
        {
        "product_id": "12345",
        "productName": "BeerBrosSpecial",
        "amount": 2,
        "price": "8.45",
        "warehouse": "jees"
        }, 
        {
        "product_id": "12345",
        "productName": "BeerBrosSpecial",
        "amount": 2,
        "price": "8.45",
        "warehouse": "jees"
        }
    ],  
    "firstName": "Mr.Kekko",
    "lastName": "Bar",
    "adress": "Jan-Magnussons Plats 2",
    "postCode": "00560",
    "postalDistrict": "Helsinki",
    "country": "Finland",
    "phoneNumber": "0451240567",
    "email": "fooo.barsson123@gmail.com",
    "orderType": "Home delivery",
    "payment": "Visa"
    
}

###
