@baseURL = https://cna-orders.azurewebsites.net

//@baseURL = http://localhost:3080
@token = Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJTZWN1cml0eSBTZXJ2aWNlICgxLjAuMCkiLCJleHAiOjE2Njg1MTg0OTUsInN1YiI6IjYzNWJlMDkwZjFkMWJhN2NiMTdhNWY4YSIsImRhdGEiOnsiZmlyc3ROYW1lIjoiSm9obiIsImxhc3ROYW1lIjoiRG9lIiwiYWRkcmVzcyI6Ikphbi1NYWdudXMgSmFuc3NvbmluIGF1a2lvIDEiLCJwb3N0YWxDb2RlIjoiNTUwIiwiY2l0eSI6IkhlbHNpbmtpIiwiY291bnRyeSI6IkZpbmxhbmQiLCJlbWFpbCI6ImpvaG4uZG9lQGFyY2FkYS5maSJ9LCJpYXQiOjE2Njg1MTEyOTV9.HM7tSskvQohrajOZWDSDYwrrQobzgsIZ7I-HExkg2tAOJixTHKTGiBeg0SBgWa8N2H2yc_bRfDH80QMf5ddJXDhxP56sIpgj1xbLoBahG8X50aRz4vixZcMj-McTQgV9OaBqfhtYsWkwpAkJVpCR3ItjG1mJAQE1SMTForWa8hYQzhhZBidnRy68nYx4vM552WUOML-qHokZo_R5jOL9fdarmbAKoOTNG7ns7OnpGZqjUZpcsa8PzTFaDixGAO_mIdQ52HwRXqk-XO9YclUIKG7UhkbmtCvYOE9RoIS30REu-UTL5d8ht3xY4-sJi4D_uoSwvXYq6kJvhVrTHq5h-A

###

GET {{baseURL}}/orders/
Authorization: {{token}}
Content-Type: application/json

###

GET {{baseURL}}/orders/customers
Authorization: {{token}}
Content-Type: application/json

###

POST {{baseURL}}/orders/
Authorization: {{token}}
Content-Type: application/json

{
    "date": "2022-11-1",
    "products": [
        {
        "product_id": "12345",
        "productName": "BeerBrosSpecial",
        "amount": 2,
        "price": "8.45",
        "warehouse": "jees"
        }, 
        {
        "product_id": "12345",
        "productName": "BeerBrosSpecial",
        "amount": 2,
        "price": "8.45",
        "warehouse": "jees"
        }
    ],  
    "firstName": "Mr.Kekko",
    "lastName": "BarSS",
    "adress": "Jan-Magnussons Plats 2",
    "postCode": "00560",
    "postalDistrict": "Helsinki",
    "country": "Finland",
    "phoneNumber": "0451240567",
    "email": "fooo.barsson123@gmail.com",
    "orderType": "Home delivery",
    "payment": "Visa"
    
}

###


